name: release

on:
  push:
    branches:
      - main
      - 'dev-v3-*'
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Print env
        run: node -p "[process.env.GITHUB_REF_TYPE, process.env.GITHUB_REF_NAME]"
